### ISSUE TITLE
VET Balance Mismatch on Explorer.

### ISSUE THREAD

**Issue by shaswatsaloni** [vechain/VIPs#72]
Hi All,

I am having a mismatch while calculating the balance for a particular address (**0x9a1e4bf6c41f50c399a128ab588fe4e4883bd872**)
from explorer (https://explore.vechain.org/accounts/0x9a1e4bf6c41f50c399a128ab588fe4e4883bd872/txs) .

I have added the **Ins** and subtract the **Outs**, but seems like not coming what is mentioned on explorer (https://explore.vechain.org/accounts/0x9a1e4bf6c41f50c399a128ab588fe4e4883bd872/) . Can anyone help me with this?

Thanks,
Saloni.

**Comment by qianbin** [comment]
Hi, @shaswatsaloni. Thanks for your report. 
The address *0x9a1e4bf6c41f50c399a128ab588fe4e4883bd872* was the address of an authority node, and its balance was initially set as 25m, which is not shown in transfer logs.

**Comment by shaswatsaloni** [comment]
Hi @qianbin , Thanks for quick response. I have around **42 addresses** for which I have the same case. Can you share me the list of addresses which are an address of an authority node. I am attaching the csv files for the list of addresses for which we have negative balance.   

Thanks,
Saloni.

**Comment by shaswatsaloni** [comment]
[Vet_Negative.xlsx](https://github.com/vechain/VIPs/files/14927101/Vet_Negative.xlsx)

**Comment by libotony** [comment]
https://github.com/vechain/thor/blob/master/genesis/mainnet.go#L64-L96

Filled with 21,046,908,616.5 VET each

and 

https://github.com/vechain/thor/blob/master/genesis/mainnet.go#L64-L96

The second one in the line filled with 25,000,000 VET each

**Comment by shaswatsaloni** [comment]
Hi, 
Can we get the genesis.json for Vet. So that from next time we will not get these negative balances?

Thanks,
Saloni.

**Comment by libotony** [comment]
> Hi, Can we get the genesis.json for Vet. So that from next time we will not get these negative balances?
> 
> Thanks, Saloni.

We don't have genesis JSON, only the go file.

**Comment by shaswatsaloni** [comment]
Okay, can you share that?

**Comment by libotony** [comment]
> https://github.com/vechain/thor/blob/master/genesis/mainnet.go#L64-L96
> 
> Filled with 21,046,908,616.5 VET each
> 
> and
> 
> https://github.com/vechain/thor/blob/master/genesis/mainnet.go#L64-L96
> 
> The second one in the line filled with 25,000,000 VET each

@shaswatsaloni Here

**Comment by shaswatsaloni** [comment]
Hi @libotony , thanks for this info, but here in these lines, we have only few addresses mentioned but I have around 42 of them. So, can you have a look once and confirm?

I am sharing the list of addresses and balances with you.
[Vet_Negative.xlsx](https://github.com/vechain/VIPs/files/14957207/Vet_Negative.xlsx)

Thanks,
Saloni.

**Comment by ifavo** [comment]
@shaswatsaloni have you checked the bottom of the file?

https://github.com/vechain/thor/blob/master/genesis/mainnet.go#L160-L263

**Comment by shaswatsaloni** [comment]
Okay, @ifavo, checked. I will verify if these are all the addresses that we have negative balance with.

Thanks for the help.

**Comment by shaswatsaloni** [comment]
Hi @ifavo, we have a full node running for Vechain, is the authority node concept was there earlier. Or is it newly introduced?

Thanks,
Saloni

**Comment by shaswatsaloni** [comment]
Hey, following up here?

**Comment by libotony** [comment]
> Hi @ifavo, we have a full node running for Vechain, is the authority node concept was there earlier? Or is it newly introduced?
> 
> I have few queries.
> 
> 1. Do we need to setup the authority node to get these genesis data or is there any other way by which we can integrate it?
> 2. How can we get the amount that is associated with the authority node address at genesis?
> 3. Is the authority node address keeps growing in numbers as the node size increases or is it decided at the initial stage?
> 
> Thanks, Saloni

Genesis info is public, you can access it via the link posted above. I think for your use case, the only thing you need to consider is pre-allocated funds in the genesis. I will again, post the links for the pre-allocated accounts.

https://github.com/vechain/thor/blob/master/genesis/mainnet.go#L64-L96

Filled with 21,046,908,616.5 VET each

and

https://github.com/vechain/thor/blob/master/genesis/mainnet.go#L160-L263

The second address in the line filled with 25,000,000 VET each

**Comment by shaswatsaloni** [comment]
Thanks, @libotony , but can you help me with the 3rd question?

**Comment by libotony** [comment]
> Thanks, @libotony , but can you help me with the 3rd question?

The pre-allocated account balance only happens one time when the network is launched.
